This is a notebook for training using CatBoostRegressor (CBR).

In [1]:
import pandas as pd
from sklearn.preprocessing import LabelEncoder, StandardScaler
from sklearn.model_selection import train_test_split, GridSearchCV
from sklearn.metrics import root_mean_squared_error
from catboost import CatBoostRegressor

In [2]:
# Load the data
# train_df = pd.read_csv('./inputs/train.csv').set_index("id")
%store -r train_df
train_df = train_df
target = train_df["Listening_Time_minutes"]
train_df.drop("Listening_Time_minutes", axis=1, inplace=True)
# train_df.drop("Episode_Title", axis=1, inplace=True)
train_df

,Podcast_Name,Episode_Title,Episode_Length_minutes,Genre,Host_Popularity_percentage,Publication_Day,Publication_Time,Guest_Popularity_percentage,Number_of_Ads,Episode_Sentiment
id,,,,,,,,,,
0,Mystery Matters,Episode 98,46.5033,True Crime,74.81,Thursday,Night,56.8075,0.0,Positive
1,Joke Junction,Episode 26,119.8000,Comedy,66.95,Saturday,Afternoon,75.9500,2.0,Negative
2,Study Sessions,Episode 16,73.9000,Education,69.97,Tuesday,Evening,8.9700,0.0,Negative
3,Digital Digest,Episode 45,67.1700,Technology,57.22,Monday,Morning,78.7000,2.0,Positive
4,Mind & Body,Episode 86,110.5100,Health,80.07,Monday,Afternoon,58.6800,3.0,Neutral
...,...,...,...,...,...,...,...,...,...,...
749995,Learning Lab,Episode 25,75.6600,Education,69.36,Saturday,Morning,55.0653,0.0,Negative
749996,Business Briefs,Episode 21,75.7500,Business,35.21,Saturday,Night,49.5326,2.0,Neutral
749997,Lifestyle Lounge,Episode 51,30.9800,Lifestyle,78.58,Thursday,Morning,84.8900,0.0,Negative
749998,Style Guide,Episode 47,108.9800,Lifestyle,45.39,Thursday,Morning,93.2700,0.0,Negative
749999,Sports Central,Episode 99,24.1000,Sports,22.45,Saturday,Night,36.7200,0.0,Neutral

In [3]:
# Encode the categorical columns
%store -r categories
# categories = categories[:1] + categories[2:]
display(categories)
encoder = LabelEncoder()
for column in categories:
    train_df[column] = encoder.fit_transform(train_df[column])

train_df[categories]

Index(['Podcast_Name', 'Episode_Title', 'Genre', 'Publication_Day',
       'Publication_Time', 'Episode_Sentiment'],
      dtype='object')

,Podcast_Name,Episode_Title,Genre,Publication_Day,Publication_Time,Episode_Sentiment
id,,,,,,
0,34,98,9,4,3,2
1,24,19,1,2,0,0
2,40,8,2,5,1,0
3,10,40,8,1,2,2
4,31,85,3,1,0,1
...,...,...,...,...,...,...
749995,26,18,2,2,2,0
749996,2,14,0,2,3,1
749997,28,47,4,4,2,0
749998,41,42,4,4,2,0
749999,38,99,7,2,3,1

In [4]:
# Scale the data
scaler = StandardScaler()
train_df_scaled = scaler.fit_transform(train_df)
train_df_scaled

array([[ 0.74158935,  1.69278629, -0.5419192 , ...,  0.18069978,
        -1.17176445,  1.22882316],
       [ 0.03425408, -1.10995773,  1.70156706, ...,  0.92637313,
         0.56565891, -1.22384261],
       [ 1.16599051, -1.50021322,  0.2966468 , ..., -1.68275323,
        -1.17176445, -1.22384261],
       ...,
       [ 0.31718819, -0.1165801 , -1.01706078, ...,  1.27462022,
        -1.17176445, -1.22384261],
       [ 1.23672404, -0.29396896,  1.37038542, ...,  1.60105317,
        -1.17176445, -1.22384261],
       [ 1.02452346,  1.72826406, -1.22764578, ..., -0.60178493,
        -1.17176445,  0.00249027]])

In [5]:
X_train, X_test, y_train, y_test = train_test_split(train_df_scaled, target, test_size=0.2, random_state=42)

In [6]:
# Create the model
model = CatBoostRegressor()
model.fit(X_train, y_train)
y_pred = model.predict(X_test)
score = root_mean_squared_error(y_test, y_pred)
print(score)

Learning rate set to 0.112494
0:	learn: 24.6418725	total: 191ms	remaining: 3m 10s
1:	learn: 22.4592559	total: 238ms	remaining: 1m 58s
2:	learn: 20.5603507	total: 283ms	remaining: 1m 33s
3:	learn: 18.9172397	total: 321ms	remaining: 1m 19s
4:	learn: 17.4953844	total: 361ms	remaining: 1m 11s
5:	learn: 16.2856769	total: 406ms	remaining: 1m 7s
6:	learn: 15.2574615	total: 464ms	remaining: 1m 5s
7:	learn: 14.3793461	total: 506ms	remaining: 1m 2s
8:	learn: 13.6387467	total: 548ms	remaining: 1m
9:	learn: 13.0112737	total: 588ms	remaining: 58.2s
10:	learn: 12.4880019	total: 633ms	remaining: 56.9s
11:	learn: 12.0521945	total: 688ms	remaining: 56.6s
12:	learn: 11.6969587	total: 735ms	remaining: 55.8s
13:	learn: 11.4056528	total: 780ms	remaining: 54.9s
14:	learn: 11.1655526	total: 819ms	remaining: 53.8s
15:	learn: 10.9684523	total: 861ms	remaining: 53s
16:	learn: 10.8100753	total: 945ms	remaining: 54.7s
17:	learn: 10.6761824	total: 986ms	remaining: 53.8s
18:	learn: 10.5696873	total: 1.03s	remaining: 53.1s
19:	learn: 10.4822313	total: 1.07s	remaining: 52.3s
20:	learn: 10.4117731	total: 1.11s	remaining: 51.8s
21:	learn: 10.3528576	total: 1.15s	remaining: 51.2s
22:	learn: 10.3050336	total: 1.2s	remaining: 50.8s
23:	learn: 10.2662124	total: 1.24s	remaining: 50.3s
24:	learn: 10.2349328	total: 1.28s	remaining: 49.8s
25:	learn: 10.2089369	total: 1.33s	remaining: 49.7s
26:	learn: 10.1874211	total: 1.36s	remaining: 49.2s
27:	learn: 10.1701814	total: 1.41s	remaining: 48.8s
28:	learn: 10.1559583	total: 1.45s	remaining: 48.5s
29:	learn: 10.1431163	total: 1.49s	remaining: 48.1s
30:	learn: 10.1329940	total: 1.53s	remaining: 47.9s
31:	learn: 10.1245732	total: 1.58s	remaining: 47.9s
32:	learn: 10.1178088	total: 1.63s	remaining: 47.8s
33:	learn: 10.1120739	total: 1.68s	remaining: 47.6s
34:	learn: 10.1072129	total: 1.72s	remaining: 47.4s
35:	learn: 10.1029959	total: 1.76s	remaining: 47.2s
36:	learn: 10.0990318	total: 1.81s	remaining: 47s
37:	learn: 10.0955247	total: 1.84s	remaining: 46.7s
38:	learn: 10.0923673	total: 1.89s	remaining: 46.5s
39:	learn: 10.0892701	total: 1.93s	remaining: 46.2s
40:	learn: 10.0867942	total: 1.97s	remaining: 46s
41:	learn: 10.0840908	total: 2.02s	remaining: 46s
42:	learn: 10.0823167	total: 2.06s	remaining: 45.9s
43:	learn: 10.0808409	total: 2.11s	remaining: 45.8s
44:	learn: 10.0794803	total: 2.15s	remaining: 45.6s
45:	learn: 10.0778086	total: 2.2s	remaining: 45.5s
46:	learn: 10.0764198	total: 2.24s	remaining: 45.4s
47:	learn: 10.0745993	total: 2.28s	remaining: 45.2s
48:	learn: 10.0731414	total: 2.31s	remaining: 44.9s
49:	learn: 10.0722058	total: 2.35s	remaining: 44.6s
50:	learn: 10.0712148	total: 2.38s	remaining: 44.4s
51:	learn: 10.0695478	total: 2.42s	remaining: 44.1s
52:	learn: 10.0684742	total: 2.46s	remaining: 44.1s
53:	learn: 10.0676604	total: 2.5s	remaining: 43.8s
54:	learn: 10.0663386	total: 2.54s	remaining: 43.6s
55:	learn: 10.0653713	total: 2.57s	remaining: 43.4s
56:	learn: 10.0640920	total: 2.61s	remaining: 43.2s
57:	learn: 10.0630110	total: 2.66s	remaining: 43.1s
58:	learn: 10.0618113	total: 2.7s	remaining: 43.1s
59:	learn: 10.0612730	total: 2.75s	remaining: 43s
60:	learn: 10.0602050	total: 2.79s	remaining: 42.9s
61:	learn: 10.0596474	total: 2.83s	remaining: 42.8s
62:	learn: 10.0588312	total: 2.87s	remaining: 42.6s
63:	learn: 10.0576793	total: 2.9s	remaining: 42.5s
64:	learn: 10.0571476	total: 2.96s	remaining: 42.5s
65:	learn: 10.0567225	total: 3s	remaining: 42.4s
66:	learn: 10.0556357	total: 3.03s	remaining: 42.2s
67:	learn: 10.0549453	total: 3.07s	remaining: 42s
68:	learn: 10.0544159	total: 3.1s	remaining: 41.9s
69:	learn: 10.0538323	total: 3.14s	remaining: 41.7s
70:	learn: 10.0534091	total: 3.18s	remaining: 41.6s
71:	learn: 10.0529459	total: 3.22s	remaining: 41.5s
72:	learn: 10.0523841	total: 3.26s	remaining: 41.4s
73:	learn: 10.0517475	total: 3.3s	remaining: 41.3s
74:	learn: 10.0509459	total: 3.33s	remaining: 41.1s
75:	learn: 10.0498429	total: 3.37s	remaining: 40.9s
76:	learn: 10.0490542	total: 3.4s	remaining: 40.8s
77:	learn: 10.0483984	total: 3.44s	remaining: 40.7s
78:	learn: 10.0481172	total: 3.48s	remaining: 40.6s
79:	learn: 10.0473280	total: 3.52s	remaining: 40.4s
80:	learn: 10.0464739	total: 3.55s	remaining: 40.3s
81:	learn: 10.0459562	total: 3.59s	remaining: 40.2s
82:	learn: 10.0454651	total: 3.63s	remaining: 40.1s
83:	learn: 10.0447633	total: 3.67s	remaining: 40s
84:	learn: 10.0442784	total: 3.71s	remaining: 39.9s
85:	learn: 10.0436662	total: 3.75s	remaining: 39.8s
86:	learn: 10.0432341	total: 3.78s	remaining: 39.7s
87:	learn: 10.0424918	total: 3.82s	remaining: 39.6s
88:	learn: 10.0419327	total: 3.86s	remaining: 39.5s
89:	learn: 10.0414429	total: 3.91s	remaining: 39.5s
90:	learn: 10.0408798	total: 3.96s	remaining: 39.5s
91:	learn: 10.0404750	total: 4s	remaining: 39.5s
92:	learn: 10.0398703	total: 4.03s	remaining: 39.3s
93:	learn: 10.0390728	total: 4.07s	remaining: 39.2s
94:	learn: 10.0389258	total: 4.11s	remaining: 39.1s
95:	learn: 10.0385663	total: 4.14s	remaining: 39s
96:	learn: 10.0377588	total: 4.18s	remaining: 38.9s
97:	learn: 10.0372123	total: 4.21s	remaining: 38.8s
98:	learn: 10.0364247	total: 4.25s	remaining: 38.7s
99:	learn: 10.0361805	total: 4.29s	remaining: 38.6s
100:	learn: 10.0353330	total: 4.33s	remaining: 38.5s
101:	learn: 10.0350502	total: 4.37s	remaining: 38.4s
102:	learn: 10.0344031	total: 4.4s	remaining: 38.4s
103:	learn: 10.0338491	total: 4.44s	remaining: 38.2s
104:	learn: 10.0331041	total: 4.47s	remaining: 38.1s
105:	learn: 10.0322292	total: 4.5s	remaining: 38s
106:	learn: 10.0316289	total: 4.54s	remaining: 37.9s
107:	learn: 10.0310996	total: 4.59s	remaining: 37.9s
108:	learn: 10.0309993	total: 4.63s	remaining: 37.8s
109:	learn: 10.0304500	total: 4.67s	remaining: 37.8s
110:	learn: 10.0300401	total: 4.71s	remaining: 37.7s
111:	learn: 10.0295209	total: 4.76s	remaining: 37.7s
112:	learn: 10.0288572	total: 4.8s	remaining: 37.7s
113:	learn: 10.0281960	total: 4.84s	remaining: 37.6s
114:	learn: 10.0276088	total: 4.88s	remaining: 37.5s
115:	learn: 10.0270677	total: 4.92s	remaining: 37.5s
116:	learn: 10.0265766	total: 4.96s	remaining: 37.4s
117:	learn: 10.0257893	total: 5s	remaining: 37.4s
118:	learn: 10.0255312	total: 5.03s	remaining: 37.3s
119:	learn: 10.0250623	total: 5.08s	remaining: 37.2s
120:	learn: 10.0244291	total: 5.12s	remaining: 37.2s
121:	learn: 10.0237741	total: 5.16s	remaining: 37.1s
122:	learn: 10.0230711	total: 5.19s	remaining: 37s
123:	learn: 10.0223403	total: 5.23s	remaining: 37s
124:	learn: 10.0216992	total: 5.26s	remaining: 36.9s
125:	learn: 10.0210327	total: 5.3s	remaining: 36.8s
126:	learn: 10.0203615	total: 5.33s	remaining: 36.7s
127:	learn: 10.0192628	total: 5.37s	remaining: 36.6s
128:	learn: 10.0185505	total: 5.4s	remaining: 36.5s
129:	learn: 10.0177996	total: 5.43s	remaining: 36.4s
130:	learn: 10.0173674	total: 5.48s	remaining: 36.4s
131:	learn: 10.0167109	total: 5.51s	remaining: 36.3s
132:	learn: 10.0162003	total: 5.55s	remaining: 36.2s
133:	learn: 10.0156447	total: 5.58s	remaining: 36.1s
134:	learn: 10.0147937	total: 5.62s	remaining: 36s
135:	learn: 10.0141439	total: 5.65s	remaining: 35.9s
136:	learn: 10.0135430	total: 5.69s	remaining: 35.8s
137:	learn: 10.0129656	total: 5.73s	remaining: 35.8s
138:	learn: 10.0124244	total: 5.76s	remaining: 35.7s
139:	learn: 10.0117623	total: 5.8s	remaining: 35.6s
140:	learn: 10.0111440	total: 5.83s	remaining: 35.5s
141:	learn: 10.0105900	total: 5.87s	remaining: 35.5s
142:	learn: 10.0100225	total: 5.92s	remaining: 35.5s
143:	learn: 10.0093376	total: 5.96s	remaining: 35.4s
144:	learn: 10.0091281	total: 5.99s	remaining: 35.3s
145:	learn: 10.0086515	total: 6.03s	remaining: 35.2s
146:	learn: 10.0078011	total: 6.06s	remaining: 35.2s
147:	learn: 10.0073776	total: 6.09s	remaining: 35.1s
148:	learn: 10.0069920	total: 6.14s	remaining: 35.1s
149:	learn: 10.0064296	total: 6.18s	remaining: 35s
150:	learn: 10.0058506	total: 6.22s	remaining: 35s
151:	learn: 10.0053171	total: 6.25s	remaining: 34.9s
152:	learn: 10.0045700	total: 6.29s	remaining: 34.8s
153:	learn: 10.0038499	total: 6.32s	remaining: 34.7s
154:	learn: 10.0035260	total: 6.36s	remaining: 34.7s
155:	learn: 10.0030931	total: 6.4s	remaining: 34.6s
156:	learn: 10.0026037	total: 6.43s	remaining: 34.5s
157:	learn: 10.0020447	total: 6.47s	remaining: 34.5s
158:	learn: 10.0018426	total: 6.5s	remaining: 34.4s
159:	learn: 10.0012464	total: 6.54s	remaining: 34.3s
160:	learn: 10.0006542	total: 6.58s	remaining: 34.3s
161:	learn: 10.0001352	total: 6.62s	remaining: 34.3s
162:	learn: 9.9998941	total: 6.66s	remaining: 34.2s
163:	learn: 9.9996382	total: 6.69s	remaining: 34.1s
164:	learn: 9.9993438	total: 6.73s	remaining: 34.1s
165:	learn: 9.9989446	total: 6.77s	remaining: 34s
166:	learn: 9.9984183	total: 6.81s	remaining: 34s
167:	learn: 9.9975435	total: 6.84s	remaining: 33.9s
168:	learn: 9.9972083	total: 6.88s	remaining: 33.8s
169:	learn: 9.9969395	total: 6.92s	remaining: 33.8s
170:	learn: 9.9966025	total: 6.96s	remaining: 33.7s
171:	learn: 9.9961416	total: 6.99s	remaining: 33.6s
172:	learn: 9.9955139	total: 7.02s	remaining: 33.6s
173:	learn: 9.9949606	total: 7.07s	remaining: 33.5s
174:	learn: 9.9945030	total: 7.1s	remaining: 33.5s
175:	learn: 9.9943569	total: 7.13s	remaining: 33.4s
176:	learn: 9.9939712	total: 7.17s	remaining: 33.4s
177:	learn: 9.9934501	total: 7.23s	remaining: 33.4s
178:	learn: 9.9929529	total: 7.28s	remaining: 33.4s
179:	learn: 9.9925042	total: 7.33s	remaining: 33.4s
180:	learn: 9.9919305	total: 7.37s	remaining: 33.4s
181:	learn: 9.9915040	total: 7.41s	remaining: 33.3s
182:	learn: 9.9910699	total: 7.46s	remaining: 33.3s
183:	learn: 9.9905590	total: 7.5s	remaining: 33.3s
184:	learn: 9.9900070	total: 7.55s	remaining: 33.3s
185:	learn: 9.9895202	total: 7.6s	remaining: 33.3s
186:	learn: 9.9890124	total: 7.65s	remaining: 33.3s
187:	learn: 9.9886769	total: 7.69s	remaining: 33.2s
188:	learn: 9.9880551	total: 7.74s	remaining: 33.2s
189:	learn: 9.9876351	total: 7.8s	remaining: 33.2s
190:	learn: 9.9871904	total: 7.84s	remaining: 33.2s
191:	learn: 9.9867856	total: 7.88s	remaining: 33.2s
192:	learn: 9.9861828	total: 7.93s	remaining: 33.2s
193:	learn: 9.9859588	total: 7.97s	remaining: 33.1s
194:	learn: 9.9857151	total: 8.02s	remaining: 33.1s
195:	learn: 9.9854374	total: 8.06s	remaining: 33s
196:	learn: 9.9851445	total: 8.09s	remaining: 33s
197:	learn: 9.9847393	total: 8.12s	remaining: 32.9s
198:	learn: 9.9842553	total: 8.16s	remaining: 32.9s
199:	learn: 9.9836221	total: 8.21s	remaining: 32.8s
200:	learn: 9.9832138	total: 8.24s	remaining: 32.8s
201:	learn: 9.9827803	total: 8.28s	remaining: 32.7s
202:	learn: 9.9820690	total: 8.31s	remaining: 32.6s
203:	learn: 9.9815148	total: 8.35s	remaining: 32.6s
204:	learn: 9.9810892	total: 8.38s	remaining: 32.5s
205:	learn: 9.9807157	total: 8.43s	remaining: 32.5s
206:	learn: 9.9803685	total: 8.47s	remaining: 32.5s
207:	learn: 9.9800121	total: 8.51s	remaining: 32.4s
208:	learn: 9.9798266	total: 8.54s	remaining: 32.3s
209:	learn: 9.9791917	total: 8.58s	remaining: 32.3s
210:	learn: 9.9789096	total: 8.63s	remaining: 32.3s
211:	learn: 9.9785681	total: 8.67s	remaining: 32.2s
212:	learn: 9.9782135	total: 8.7s	remaining: 32.1s
213:	learn: 9.9774653	total: 8.74s	remaining: 32.1s
214:	learn: 9.9770564	total: 8.77s	remaining: 32s
215:	learn: 9.9766010	total: 8.8s	remaining: 32s
216:	learn: 9.9761089	total: 8.84s	remaining: 31.9s
217:	learn: 9.9757725	total: 8.89s	remaining: 31.9s
218:	learn: 9.9754771	total: 8.93s	remaining: 31.8s
219:	learn: 9.9749283	total: 8.96s	remaining: 31.8s
220:	learn: 9.9745096	total: 9.01s	remaining: 31.8s
221:	learn: 9.9743475	total: 9.05s	remaining: 31.7s
222:	learn: 9.9738779	total: 9.09s	remaining: 31.7s
223:	learn: 9.9735147	total: 9.13s	remaining: 31.6s
224:	learn: 9.9732423	total: 9.17s	remaining: 31.6s
225:	learn: 9.9729658	total: 9.2s	remaining: 31.5s
226:	learn: 9.9727064	total: 9.23s	remaining: 31.4s
227:	learn: 9.9722157	total: 9.27s	remaining: 31.4s
228:	learn: 9.9718626	total: 9.31s	remaining: 31.3s
229:	learn: 9.9713684	total: 9.35s	remaining: 31.3s
230:	learn: 9.9709204	total: 9.39s	remaining: 31.3s
231:	learn: 9.9706758	total: 9.43s	remaining: 31.2s
232:	learn: 9.9703716	total: 9.47s	remaining: 31.2s
233:	learn: 9.9702251	total: 9.51s	remaining: 31.1s
234:	learn: 9.9699050	total: 9.55s	remaining: 31.1s
235:	learn: 9.9696208	total: 9.58s	remaining: 31s
236:	learn: 9.9693619	total: 9.61s	remaining: 31s
237:	learn: 9.9690017	total: 9.65s	remaining: 30.9s
238:	learn: 9.9684126	total: 9.68s	remaining: 30.8s
239:	learn: 9.9680577	total: 9.72s	remaining: 30.8s
240:	learn: 9.9678856	total: 9.76s	remaining: 30.7s
241:	learn: 9.9675407	total: 9.8s	remaining: 30.7s
242:	learn: 9.9670712	total: 9.83s	remaining: 30.6s
243:	learn: 9.9666138	total: 9.87s	remaining: 30.6s
244:	learn: 9.9662368	total: 9.91s	remaining: 30.5s
245:	learn: 9.9656602	total: 9.94s	remaining: 30.5s
246:	learn: 9.9652051	total: 9.98s	remaining: 30.4s
247:	learn: 9.9649480	total: 10s	remaining: 30.4s
248:	learn: 9.9645606	total: 10.1s	remaining: 30.3s
249:	learn: 9.9642100	total: 10.1s	remaining: 30.3s
250:	learn: 9.9637077	total: 10.1s	remaining: 30.2s
251:	learn: 9.9633366	total: 10.2s	remaining: 30.1s
252:	learn: 9.9630668	total: 10.2s	remaining: 30.1s
253:	learn: 9.9626758	total: 10.2s	remaining: 30.1s
254:	learn: 9.9622896	total: 10.3s	remaining: 30s
255:	learn: 9.9618232	total: 10.3s	remaining: 30s
256:	learn: 9.9614276	total: 10.3s	remaining: 29.9s
257:	learn: 9.9611442	total: 10.4s	remaining: 29.8s
258:	learn: 9.9608964	total: 10.4s	remaining: 29.8s
259:	learn: 9.9606126	total: 10.5s	remaining: 29.8s
260:	learn: 9.9604370	total: 10.5s	remaining: 29.7s
261:	learn: 9.9599974	total: 10.5s	remaining: 29.6s
262:	learn: 9.9596026	total: 10.6s	remaining: 29.6s
263:	learn: 9.9591561	total: 10.6s	remaining: 29.6s
264:	learn: 9.9587989	total: 10.6s	remaining: 29.5s
265:	learn: 9.9585960	total: 10.7s	remaining: 29.5s
266:	learn: 9.9582292	total: 10.7s	remaining: 29.4s
267:	learn: 9.9578777	total: 10.8s	remaining: 29.4s
268:	learn: 9.9575186	total: 10.8s	remaining: 29.4s
269:	learn: 9.9571343	total: 10.8s	remaining: 29.3s
270:	learn: 9.9568422	total: 10.9s	remaining: 29.3s
271:	learn: 9.9563674	total: 10.9s	remaining: 29.2s
272:	learn: 9.9559642	total: 11s	remaining: 29.2s
273:	learn: 9.9556826	total: 11s	remaining: 29.1s
274:	learn: 9.9553128	total: 11s	remaining: 29.1s
275:	learn: 9.9550377	total: 11.1s	remaining: 29.1s
276:	learn: 9.9548108	total: 11.1s	remaining: 29s
277:	learn: 9.9544482	total: 11.2s	remaining: 29s
278:	learn: 9.9540982	total: 11.2s	remaining: 29s
279:	learn: 9.9538537	total: 11.3s	remaining: 28.9s
280:	learn: 9.9536068	total: 11.3s	remaining: 28.9s
281:	learn: 9.9530811	total: 11.3s	remaining: 28.9s
282:	learn: 9.9526560	total: 11.4s	remaining: 28.8s
283:	learn: 9.9524396	total: 11.4s	remaining: 28.8s
284:	learn: 9.9520677	total: 11.5s	remaining: 28.7s
285:	learn: 9.9516713	total: 11.5s	remaining: 28.7s
286:	learn: 9.9512660	total: 11.5s	remaining: 28.7s
287:	learn: 9.9508434	total: 11.6s	remaining: 28.6s
288:	learn: 9.9505201	total: 11.6s	remaining: 28.6s
289:	learn: 9.9501804	total: 11.7s	remaining: 28.5s
290:	learn: 9.9498428	total: 11.7s	remaining: 28.5s
291:	learn: 9.9496817	total: 11.7s	remaining: 28.5s
292:	learn: 9.9491666	total: 11.8s	remaining: 28.5s
293:	learn: 9.9487519	total: 11.8s	remaining: 28.4s
294:	learn: 9.9482426	total: 11.9s	remaining: 28.4s
295:	learn: 9.9477841	total: 12s	remaining: 28.4s
296:	learn: 9.9473723	total: 12s	remaining: 28.4s
297:	learn: 9.9469792	total: 12s	remaining: 28.4s
298:	learn: 9.9465758	total: 12.1s	remaining: 28.4s
299:	learn: 9.9462216	total: 12.1s	remaining: 28.3s
300:	learn: 9.9458177	total: 12.2s	remaining: 28.3s
301:	learn: 9.9455083	total: 12.2s	remaining: 28.3s
302:	learn: 9.9452017	total: 12.3s	remaining: 28.2s
303:	learn: 9.9449028	total: 12.3s	remaining: 28.2s
304:	learn: 9.9446538	total: 12.3s	remaining: 28.1s
305:	learn: 9.9442996	total: 12.4s	remaining: 28.1s
306:	learn: 9.9440374	total: 12.4s	remaining: 28.1s
307:	learn: 9.9436570	total: 12.5s	remaining: 28s
308:	learn: 9.9433020	total: 12.5s	remaining: 28s
309:	learn: 9.9428133	total: 12.6s	remaining: 28s
310:	learn: 9.9423837	total: 12.6s	remaining: 27.9s
311:	learn: 9.9421011	total: 12.6s	remaining: 27.9s
312:	learn: 9.9417745	total: 12.7s	remaining: 27.8s
313:	learn: 9.9414015	total: 12.7s	remaining: 27.8s
314:	learn: 9.9411466	total: 12.8s	remaining: 27.8s
315:	learn: 9.9408789	total: 12.8s	remaining: 27.7s
316:	learn: 9.9405998	total: 12.8s	remaining: 27.7s
317:	learn: 9.9402170	total: 12.9s	remaining: 27.7s
318:	learn: 9.9399849	total: 12.9s	remaining: 27.6s
319:	learn: 9.9395750	total: 13s	remaining: 27.6s
320:	learn: 9.9392384	total: 13s	remaining: 27.6s
321:	learn: 9.9388712	total: 13.1s	remaining: 27.6s
322:	learn: 9.9386268	total: 13.1s	remaining: 27.5s
323:	learn: 9.9383274	total: 13.2s	remaining: 27.5s
324:	learn: 9.9381193	total: 13.2s	remaining: 27.5s
325:	learn: 9.9378080	total: 13.3s	remaining: 27.4s
326:	learn: 9.9374515	total: 13.3s	remaining: 27.4s
327:	learn: 9.9371932	total: 13.4s	remaining: 27.4s
328:	learn: 9.9368394	total: 13.4s	remaining: 27.3s
329:	learn: 9.9365475	total: 13.4s	remaining: 27.3s
330:	learn: 9.9361423	total: 13.5s	remaining: 27.3s
331:	learn: 9.9359691	total: 13.5s	remaining: 27.2s
332:	learn: 9.9358125	total: 13.6s	remaining: 27.2s
333:	learn: 9.9355897	total: 13.6s	remaining: 27.2s
334:	learn: 9.9354093	total: 13.7s	remaining: 27.1s
335:	learn: 9.9351720	total: 13.7s	remaining: 27.1s
336:	learn: 9.9349353	total: 13.7s	remaining: 27.1s
337:	learn: 9.9346946	total: 13.8s	remaining: 27s
338:	learn: 9.9345415	total: 13.8s	remaining: 27s
339:	learn: 9.9344092	total: 13.9s	remaining: 26.9s
340:	learn: 9.9340904	total: 13.9s	remaining: 26.9s
341:	learn: 9.9337504	total: 14s	remaining: 26.9s
342:	learn: 9.9334523	total: 14s	remaining: 26.8s
343:	learn: 9.9330933	total: 14.1s	remaining: 26.8s
344:	learn: 9.9328911	total: 14.1s	remaining: 26.8s
345:	learn: 9.9324982	total: 14.2s	remaining: 26.8s
346:	learn: 9.9321168	total: 14.3s	remaining: 26.8s
347:	learn: 9.9319602	total: 14.3s	remaining: 26.8s
348:	learn: 9.9315054	total: 14.3s	remaining: 26.8s
349:	learn: 9.9312855	total: 14.4s	remaining: 26.7s
350:	learn: 9.9309504	total: 14.4s	remaining: 26.7s
351:	learn: 9.9306730	total: 14.5s	remaining: 26.6s
352:	learn: 9.9304032	total: 14.5s	remaining: 26.6s
353:	learn: 9.9302619	total: 14.6s	remaining: 26.6s
354:	learn: 9.9299761	total: 14.6s	remaining: 26.5s
355:	learn: 9.9297261	total: 14.6s	remaining: 26.5s
356:	learn: 9.9293187	total: 14.7s	remaining: 26.5s
357:	learn: 9.9289235	total: 14.7s	remaining: 26.4s
358:	learn: 9.9286830	total: 14.8s	remaining: 26.4s
359:	learn: 9.9282255	total: 14.8s	remaining: 26.4s
360:	learn: 9.9280489	total: 14.9s	remaining: 26.3s
361:	learn: 9.9276358	total: 14.9s	remaining: 26.3s
362:	learn: 9.9272765	total: 15s	remaining: 26.3s
363:	learn: 9.9268881	total: 15s	remaining: 26.2s
364:	learn: 9.9266646	total: 15s	remaining: 26.2s
365:	learn: 9.9264897	total: 15.1s	remaining: 26.1s
366:	learn: 9.9261848	total: 15.1s	remaining: 26.1s
367:	learn: 9.9260120	total: 15.2s	remaining: 26s
368:	learn: 9.9259026	total: 15.2s	remaining: 26s
369:	learn: 9.9255553	total: 15.3s	remaining: 26s
370:	learn: 9.9251958	total: 15.3s	remaining: 25.9s
371:	learn: 9.9248630	total: 15.3s	remaining: 25.9s
372:	learn: 9.9245553	total: 15.4s	remaining: 25.8s
373:	learn: 9.9240933	total: 15.4s	remaining: 25.8s
374:	learn: 9.9238028	total: 15.5s	remaining: 25.8s
375:	learn: 9.9234653	total: 15.5s	remaining: 25.7s
376:	learn: 9.9231266	total: 15.6s	remaining: 25.7s
377:	learn: 9.9229656	total: 15.6s	remaining: 25.7s
378:	learn: 9.9224556	total: 15.7s	remaining: 25.6s
379:	learn: 9.9221920	total: 15.7s	remaining: 25.6s
380:	learn: 9.9218806	total: 15.7s	remaining: 25.5s
381:	learn: 9.9216270	total: 15.8s	remaining: 25.5s
382:	learn: 9.9213551	total: 15.8s	remaining: 25.5s
383:	learn: 9.9210807	total: 15.8s	remaining: 25.4s
384:	learn: 9.9207835	total: 15.9s	remaining: 25.4s

In [13]:
# Trying to find the best parameters for the CatBoost Model using GridSearchCV
parameter = {
    "random_state": [21, 34, 42, 50, 1],
}
base_model = CatBoostRegressor(n_estimators=1000, learning_rate=0.11249399930238724, max_depth=6)
grid = GridSearchCV(estimator=base_model, param_grid=parameter, scoring='neg_root_mean_squared_error', n_jobs=-1,
                    verbose=3)
grid.fit(X_train, y_train)
predictions = grid.predict(X_test)
score = root_mean_squared_error(y_test, y_pred)
print(score)

Fitting 5 folds for each of 5 candidates, totalling 25 fits
0:	learn: 24.6391500	total: 63.2ms	remaining: 1m 3s
1:	learn: 22.4617009	total: 121ms	remaining: 1m
2:	learn: 20.5646176	total: 179ms	remaining: 59.5s
3:	learn: 18.9224517	total: 248ms	remaining: 1m 1s
4:	learn: 17.5032884	total: 325ms	remaining: 1m 4s
5:	learn: 16.2866912	total: 384ms	remaining: 1m 3s
6:	learn: 15.2399863	total: 451ms	remaining: 1m 3s
7:	learn: 14.3635708	total: 518ms	remaining: 1m 4s
8:	learn: 13.6154723	total: 590ms	remaining: 1m 4s
9:	learn: 12.9952774	total: 656ms	remaining: 1m 4s
10:	learn: 12.4727782	total: 719ms	remaining: 1m 4s
11:	learn: 12.0479063	total: 783ms	remaining: 1m 4s
12:	learn: 11.6978792	total: 852ms	remaining: 1m 4s
13:	learn: 11.4063220	total: 910ms	remaining: 1m 4s
14:	learn: 11.1642215	total: 969ms	remaining: 1m 3s
15:	learn: 10.9694541	total: 1.03s	remaining: 1m 3s
16:	learn: 10.8069913	total: 1.09s	remaining: 1m 3s
17:	learn: 10.6765070	total: 1.16s	remaining: 1m 3s
18:	learn: 10.5689360	total: 1.21s	remaining: 1m 2s
19:	learn: 10.4831881	total: 1.27s	remaining: 1m 2s
20:	learn: 10.4148950	total: 1.34s	remaining: 1m 2s
21:	learn: 10.3548239	total: 1.42s	remaining: 1m 2s
22:	learn: 10.3079798	total: 1.48s	remaining: 1m 2s
23:	learn: 10.2687663	total: 1.54s	remaining: 1m 2s
24:	learn: 10.2374825	total: 1.6s	remaining: 1m 2s
25:	learn: 10.2108624	total: 1.65s	remaining: 1m 1s
26:	learn: 10.1891465	total: 1.72s	remaining: 1m 1s
27:	learn: 10.1715977	total: 1.78s	remaining: 1m 1s
28:	learn: 10.1571576	total: 1.83s	remaining: 1m 1s
29:	learn: 10.1448637	total: 1.89s	remaining: 1m 1s
30:	learn: 10.1346974	total: 1.95s	remaining: 1m
31:	learn: 10.1263248	total: 2s	remaining: 1m
32:	learn: 10.1194575	total: 2.06s	remaining: 1m
33:	learn: 10.1133939	total: 2.12s	remaining: 1m
34:	learn: 10.1082019	total: 2.18s	remaining: 1m
35:	learn: 10.1038585	total: 2.25s	remaining: 1m
36:	learn: 10.0999298	total: 2.33s	remaining: 1m
37:	learn: 10.0966822	total: 2.4s	remaining: 1m
38:	learn: 10.0934970	total: 2.48s	remaining: 1m 1s
39:	learn: 10.0909848	total: 2.58s	remaining: 1m 1s
40:	learn: 10.0885124	total: 2.69s	remaining: 1m 2s
41:	learn: 10.0862183	total: 2.81s	remaining: 1m 4s
42:	learn: 10.0842144	total: 2.88s	remaining: 1m 4s
43:	learn: 10.0819580	total: 2.95s	remaining: 1m 4s
44:	learn: 10.0801081	total: 3.02s	remaining: 1m 4s
45:	learn: 10.0787404	total: 3.08s	remaining: 1m 3s
46:	learn: 10.0770376	total: 3.14s	remaining: 1m 3s
47:	learn: 10.0756991	total: 3.21s	remaining: 1m 3s
48:	learn: 10.0740788	total: 3.27s	remaining: 1m 3s
49:	learn: 10.0728808	total: 3.33s	remaining: 1m 3s
50:	learn: 10.0720507	total: 3.38s	remaining: 1m 2s
51:	learn: 10.0709572	total: 3.44s	remaining: 1m 2s
52:	learn: 10.0697075	total: 3.5s	remaining: 1m 2s
53:	learn: 10.0684121	total: 3.56s	remaining: 1m 2s
54:	learn: 10.0672959	total: 3.62s	remaining: 1m 2s
55:	learn: 10.0665313	total: 3.68s	remaining: 1m 2s
56:	learn: 10.0655836	total: 3.73s	remaining: 1m 1s
57:	learn: 10.0645678	total: 3.79s	remaining: 1m 1s
58:	learn: 10.0637923	total: 3.84s	remaining: 1m 1s
59:	learn: 10.0627650	total: 3.89s	remaining: 1m
60:	learn: 10.0620326	total: 3.95s	remaining: 1m
61:	learn: 10.0610962	total: 4.02s	remaining: 1m
62:	learn: 10.0598290	total: 4.08s	remaining: 1m
63:	learn: 10.0589507	total: 4.14s	remaining: 1m
64:	learn: 10.0576170	total: 4.21s	remaining: 1m
65:	learn: 10.0569986	total: 4.28s	remaining: 1m
66:	learn: 10.0566246	total: 4.34s	remaining: 1m
67:	learn: 10.0557934	total: 4.4s	remaining: 1m
68:	learn: 10.0549069	total: 4.46s	remaining: 1m
69:	learn: 10.0540609	total: 4.53s	remaining: 1m
70:	learn: 10.0530427	total: 4.59s	remaining: 1m
71:	learn: 10.0519927	total: 4.65s	remaining: 59.9s
72:	learn: 10.0514788	total: 4.71s	remaining: 59.8s
73:	learn: 10.0509789	total: 4.77s	remaining: 59.7s
74:	learn: 10.0502786	total: 4.83s	remaining: 59.5s
75:	learn: 10.0493101	total: 4.88s	remaining: 59.3s
76:	learn: 10.0489755	total: 4.93s	remaining: 59.1s
77:	learn: 10.0484786	total: 4.99s	remaining: 59s
78:	learn: 10.0479907	total: 5.04s	remaining: 58.8s
79:	learn: 10.0476145	total: 5.09s	remaining: 58.6s
80:	learn: 10.0472611	total: 5.14s	remaining: 58.4s
81:	learn: 10.0468980	total: 5.2s	remaining: 58.2s
82:	learn: 10.0460417	total: 5.25s	remaining: 58s
83:	learn: 10.0454716	total: 5.31s	remaining: 57.9s
84:	learn: 10.0451133	total: 5.36s	remaining: 57.7s
85:	learn: 10.0444006	total: 5.42s	remaining: 57.6s
86:	learn: 10.0438066	total: 5.46s	remaining: 57.4s
87:	learn: 10.0432758	total: 5.51s	remaining: 57.1s
88:	learn: 10.0424739	total: 5.56s	remaining: 56.9s
89:	learn: 10.0416541	total: 5.62s	remaining: 56.8s
90:	learn: 10.0409385	total: 5.67s	remaining: 56.6s
91:	learn: 10.0401705	total: 5.71s	remaining: 56.4s
92:	learn: 10.0391145	total: 5.76s	remaining: 56.2s
93:	learn: 10.0383264	total: 5.82s	remaining: 56.1s
94:	learn: 10.0378863	total: 5.87s	remaining: 55.9s
95:	learn: 10.0373860	total: 5.91s	remaining: 55.7s
96:	learn: 10.0369983	total: 5.97s	remaining: 55.6s
97:	learn: 10.0364607	total: 6.01s	remaining: 55.4s
98:	learn: 10.0356730	total: 6.08s	remaining: 55.3s
99:	learn: 10.0352692	total: 6.12s	remaining: 55.1s
100:	learn: 10.0349012	total: 6.17s	remaining: 54.9s
101:	learn: 10.0344978	total: 6.23s	remaining: 54.8s
102:	learn: 10.0338115	total: 6.28s	remaining: 54.7s
103:	learn: 10.0332599	total: 6.34s	remaining: 54.6s
104:	learn: 10.0329246	total: 6.39s	remaining: 54.5s
105:	learn: 10.0320843	total: 6.45s	remaining: 54.4s
106:	learn: 10.0315246	total: 6.5s	remaining: 54.2s
107:	learn: 10.0307889	total: 6.54s	remaining: 54s
108:	learn: 10.0301966	total: 6.6s	remaining: 53.9s
109:	learn: 10.0295602	total: 6.66s	remaining: 53.9s
110:	learn: 10.0288517	total: 6.71s	remaining: 53.8s
111:	learn: 10.0284571	total: 6.76s	remaining: 53.6s
112:	learn: 10.0278526	total: 6.82s	remaining: 53.5s
113:	learn: 10.0272593	total: 6.88s	remaining: 53.4s
114:	learn: 10.0266808	total: 6.92s	remaining: 53.3s
115:	learn: 10.0263027	total: 6.97s	remaining: 53.1s
116:	learn: 10.0257993	total: 7.03s	remaining: 53s
117:	learn: 10.0252070	total: 7.08s	remaining: 52.9s
118:	learn: 10.0243745	total: 7.13s	remaining: 52.8s
119:	learn: 10.0238078	total: 7.18s	remaining: 52.7s
120:	learn: 10.0230754	total: 7.23s	remaining: 52.6s
121:	learn: 10.0225791	total: 7.29s	remaining: 52.5s
122:	learn: 10.0221650	total: 7.35s	remaining: 52.4s
123:	learn: 10.0216666	total: 7.4s	remaining: 52.3s
124:	learn: 10.0212014	total: 7.45s	remaining: 52.2s
125:	learn: 10.0208035	total: 7.5s	remaining: 52.1s
126:	learn: 10.0203791	total: 7.55s	remaining: 51.9s
127:	learn: 10.0199347	total: 7.61s	remaining: 51.9s
128:	learn: 10.0194240	total: 7.67s	remaining: 51.8s
129:	learn: 10.0188349	total: 7.72s	remaining: 51.7s
130:	learn: 10.0181700	total: 7.77s	remaining: 51.5s
131:	learn: 10.0175258	total: 7.82s	remaining: 51.4s
132:	learn: 10.0169462	total: 7.87s	remaining: 51.3s
133:	learn: 10.0164501	total: 7.92s	remaining: 51.2s
134:	learn: 10.0158990	total: 7.97s	remaining: 51.1s
135:	learn: 10.0153879	total: 8.02s	remaining: 51s
136:	learn: 10.0149004	total: 8.07s	remaining: 50.9s
137:	learn: 10.0141158	total: 8.12s	remaining: 50.7s
138:	learn: 10.0136223	total: 8.18s	remaining: 50.7s
139:	learn: 10.0131780	total: 8.23s	remaining: 50.6s
140:	learn: 10.0125747	total: 8.28s	remaining: 50.4s
141:	learn: 10.0114898	total: 8.34s	remaining: 50.4s
142:	learn: 10.0110114	total: 8.39s	remaining: 50.3s
143:	learn: 10.0102089	total: 8.44s	remaining: 50.2s
144:	learn: 10.0095943	total: 8.5s	remaining: 50.1s
145:	learn: 10.0090470	total: 8.56s	remaining: 50.1s
146:	learn: 10.0085993	total: 8.61s	remaining: 50s
147:	learn: 10.0081401	total: 8.66s	remaining: 49.9s
148:	learn: 10.0076213	total: 8.71s	remaining: 49.8s
149:	learn: 10.0071833	total: 8.76s	remaining: 49.7s
150:	learn: 10.0068352	total: 8.82s	remaining: 49.6s
151:	learn: 10.0063578	total: 8.88s	remaining: 49.5s
152:	learn: 10.0057098	total: 8.93s	remaining: 49.4s
153:	learn: 10.0050763	total: 8.99s	remaining: 49.4s
154:	learn: 10.0047473	total: 9.04s	remaining: 49.3s
155:	learn: 10.0043169	total: 9.09s	remaining: 49.2s
156:	learn: 10.0039608	total: 9.14s	remaining: 49.1s
157:	learn: 10.0033680	total: 9.2s	remaining: 49s
158:	learn: 10.0027182	total: 9.25s	remaining: 48.9s
159:	learn: 10.0020564	total: 9.3s	remaining: 48.8s
160:	learn: 10.0015060	total: 9.35s	remaining: 48.7s
161:	learn: 10.0011688	total: 9.41s	remaining: 48.7s
162:	learn: 10.0007740	total: 9.46s	remaining: 48.6s
163:	learn: 10.0004610	total: 9.5s	remaining: 48.4s
164:	learn: 9.9999483	total: 9.55s	remaining: 48.3s
165:	learn: 9.9994943	total: 9.61s	remaining: 48.3s
166:	learn: 9.9990844	total: 9.67s	remaining: 48.2s
167:	learn: 9.9979578	total: 9.72s	remaining: 48.2s
168:	learn: 9.9974704	total: 9.78s	remaining: 48.1s
169:	learn: 9.9969532	total: 9.84s	remaining: 48s
170:	learn: 9.9965082	total: 9.9s	remaining: 48s
171:	learn: 9.9959999	total: 9.95s	remaining: 47.9s
172:	learn: 9.9953977	total: 10s	remaining: 47.8s
173:	learn: 9.9950496	total: 10s	remaining: 47.7s
174:	learn: 9.9947981	total: 10.1s	remaining: 47.6s
175:	learn: 9.9946046	total: 10.1s	remaining: 47.5s
176:	learn: 9.9939845	total: 10.2s	remaining: 47.4s
177:	learn: 9.9935141	total: 10.3s	remaining: 47.4s
178:	learn: 9.9928884	total: 10.3s	remaining: 47.3s
179:	learn: 9.9922269	total: 10.4s	remaining: 47.2s
180:	learn: 9.9916669	total: 10.4s	remaining: 47.2s
181:	learn: 9.9911407	total: 10.5s	remaining: 47.1s
182:	learn: 9.9908617	total: 10.5s	remaining: 47s
183:	learn: 9.9902646	total: 10.6s	remaining: 46.9s
184:	learn: 9.9898733	total: 10.6s	remaining: 46.8s
185:	learn: 9.9895068	total: 10.7s	remaining: 46.8s
186:	learn: 9.9888487	total: 10.7s	remaining: 46.7s
187:	learn: 9.9883373	total: 10.8s	remaining: 46.7s
188:	learn: 9.9880252	total: 10.9s	remaining: 46.6s
189:	learn: 9.9876828	total: 10.9s	remaining: 46.5s
190:	learn: 9.9874012	total: 11s	remaining: 46.5s
191:	learn: 9.9871585	total: 11s	remaining: 46.4s
192:	learn: 9.9866058	total: 11.1s	remaining: 46.3s
193:	learn: 9.9862132	total: 11.1s	remaining: 46.3s
194:	learn: 9.9857130	total: 11.2s	remaining: 46.2s
195:	learn: 9.9853121	total: 11.2s	remaining: 46.1s
196:	learn: 9.9846991	total: 11.3s	remaining: 46s
197:	learn: 9.9843716	total: 11.4s	remaining: 46s
198:	learn: 9.9840350	total: 11.4s	remaining: 45.9s
199:	learn: 9.9836789	total: 11.5s	remaining: 45.9s
200:	learn: 9.9832099	total: 11.5s	remaining: 45.8s
201:	learn: 9.9826097	total: 11.6s	remaining: 45.7s
202:	learn: 9.9821716	total: 11.6s	remaining: 45.7s
203:	learn: 9.9817159	total: 11.7s	remaining: 45.6s
204:	learn: 9.9813392	total: 11.7s	remaining: 45.5s
205:	learn: 9.9808503	total: 11.8s	remaining: 45.4s
206:	learn: 9.9803342	total: 11.8s	remaining: 45.3s
207:	learn: 9.9797749	total: 11.9s	remaining: 45.3s
208:	learn: 9.9793595	total: 11.9s	remaining: 45.2s
209:	learn: 9.9790305	total: 12s	remaining: 45.1s
210:	learn: 9.9787412	total: 12s	remaining: 45s
211:	learn: 9.9783796	total: 12.1s	remaining: 45s
212:	learn: 9.9779803	total: 12.2s	remaining: 44.9s
213:	learn: 9.9776472	total: 12.2s	remaining: 44.8s
214:	learn: 9.9773867	total: 12.3s	remaining: 44.8s
215:	learn: 9.9770363	total: 12.3s	remaining: 44.8s
216:	learn: 9.9765490	total: 12.4s	remaining: 44.8s
217:	learn: 9.9761639	total: 12.5s	remaining: 44.7s
218:	learn: 9.9758115	total: 12.5s	remaining: 44.6s
219:	learn: 9.9753632	total: 12.6s	remaining: 44.5s
220:	learn: 9.9748597	total: 12.6s	remaining: 44.4s
221:	learn: 9.9744811	total: 12.7s	remaining: 44.4s
222:	learn: 9.9740399	total: 12.7s	remaining: 44.3s
223:	learn: 9.9735559	total: 12.8s	remaining: 44.2s
224:	learn: 9.9731921	total: 12.8s	remaining: 44.1s
225:	learn: 9.9728931	total: 12.9s	remaining: 44.1s
226:	learn: 9.9724997	total: 12.9s	remaining: 44s
227:	learn: 9.9722587	total: 13s	remaining: 44s
228:	learn: 9.9716447	total: 13s	remaining: 43.9s
229:	learn: 9.9714851	total: 13.1s	remaining: 43.8s
230:	learn: 9.9710705	total: 13.1s	remaining: 43.8s
231:	learn: 9.9708176	total: 13.2s	remaining: 43.7s
232:	learn: 9.9703811	total: 13.3s	remaining: 43.6s
233:	learn: 9.9697995	total: 13.3s	remaining: 43.5s
234:	learn: 9.9694488	total: 13.4s	remaining: 43.5s
235:	learn: 9.9691436	total: 13.4s	remaining: 43.5s
236:	learn: 9.9688633	total: 13.5s	remaining: 43.4s
237:	learn: 9.9685828	total: 13.5s	remaining: 43.3s
238:	learn: 9.9679187	total: 13.6s	remaining: 43.3s
239:	learn: 9.9674779	total: 13.6s	remaining: 43.2s
240:	learn: 9.9671118	total: 13.7s	remaining: 43.1s
241:	learn: 9.9664412	total: 13.8s	remaining: 43.1s
242:	learn: 9.9660604	total: 13.8s	remaining: 43s
243:	learn: 9.9658480	total: 13.9s	remaining: 42.9s
244:	learn: 9.9655277	total: 13.9s	remaining: 42.9s
245:	learn: 9.9652549	total: 14s	remaining: 42.8s
246:	learn: 9.9646735	total: 14s	remaining: 42.7s
247:	learn: 9.9642471	total: 14.1s	remaining: 42.7s
248:	learn: 9.9640243	total: 14.1s	remaining: 42.6s
249:	learn: 9.9637702	total: 14.2s	remaining: 42.5s
250:	learn: 9.9635774	total: 14.2s	remaining: 42.4s
251:	learn: 9.9631308	total: 14.3s	remaining: 42.4s
252:	learn: 9.9629738	total: 14.3s	remaining: 42.3s
253:	learn: 9.9625955	total: 14.4s	remaining: 42.2s
254:	learn: 9.9622034	total: 14.4s	remaining: 42.2s
255:	learn: 9.9618026	total: 14.5s	remaining: 42.1s
256:	learn: 9.9613585	total: 14.5s	remaining: 42s
257:	learn: 9.9608148	total: 14.6s	remaining: 42s
258:	learn: 9.9604797	total: 14.6s	remaining: 41.9s
259:	learn: 9.9601593	total: 14.7s	remaining: 41.8s
260:	learn: 9.9598068	total: 14.8s	remaining: 41.8s
261:	learn: 9.9595053	total: 14.8s	remaining: 41.8s
262:	learn: 9.9590769	total: 14.9s	remaining: 41.7s
263:	learn: 9.9587272	total: 14.9s	remaining: 41.6s
264:	learn: 9.9585620	total: 15s	remaining: 41.5s
265:	learn: 9.9581068	total: 15s	remaining: 41.5s
266:	learn: 9.9576304	total: 15.1s	remaining: 41.4s
267:	learn: 9.9571569	total: 15.1s	remaining: 41.3s
268:	learn: 9.9568852	total: 15.2s	remaining: 41.3s
269:	learn: 9.9565154	total: 15.2s	remaining: 41.2s
270:	learn: 9.9563124	total: 15.3s	remaining: 41.1s
271:	learn: 9.9560728	total: 15.3s	remaining: 41.1s
272:	learn: 9.9556787	total: 15.4s	remaining: 41s
273:	learn: 9.9554125	total: 15.4s	remaining: 40.9s
274:	learn: 9.9551102	total: 15.5s	remaining: 40.9s
275:	learn: 9.9547279	total: 15.6s	remaining: 40.8s
276:	learn: 9.9543315	total: 15.6s	remaining: 40.7s
277:	learn: 9.9540693	total: 15.6s	remaining: 40.6s
278:	learn: 9.9537167	total: 15.7s	remaining: 40.6s
279:	learn: 9.9532735	total: 15.7s	remaining: 40.5s
280:	learn: 9.9529164	total: 15.8s	remaining: 40.4s
281:	learn: 9.9524890	total: 15.8s	remaining: 40.4s
282:	learn: 9.9521793	total: 15.9s	remaining: 40.3s
283:	learn: 9.9520267	total: 16s	remaining: 40.2s
284:	learn: 9.9516264	total: 16s	remaining: 40.2s
285:	learn: 9.9514540	total: 16.1s	remaining: 40.1s
286:	learn: 9.9510864	total: 16.1s	remaining: 40s
287:	learn: 9.9507396	total: 16.2s	remaining: 40s
288:	learn: 9.9504373	total: 16.2s	remaining: 39.9s
289:	learn: 9.9501052	total: 16.3s	remaining: 39.9s
290:	learn: 9.9497882	total: 16.3s	remaining: 39.8s
291:	learn: 9.9495207	total: 16.4s	remaining: 39.7s
292:	learn: 9.9490258	total: 16.4s	remaining: 39.7s
293:	learn: 9.9486764	total: 16.5s	remaining: 39.6s
294:	learn: 9.9484252	total: 16.5s	remaining: 39.5s
295:	learn: 9.9481514	total: 16.6s	remaining: 39.5s
296:	learn: 9.9478687	total: 16.6s	remaining: 39.4s
297:	learn: 9.9476425	total: 16.7s	remaining: 39.3s
298:	learn: 9.9471871	total: 16.8s	remaining: 39.3s
299:	learn: 9.9468792	total: 16.8s	remaining: 39.2s
300:	learn: 9.9465851	total: 16.9s	remaining: 39.2s
301:	learn: 9.9461972	total: 16.9s	remaining: 39.1s
302:	learn: 9.9457324	total: 17s	remaining: 39s
303:	learn: 9.9453940	total: 17s	remaining: 39s
304:	learn: 9.9450814	total: 17.1s	remaining: 38.9s
305:	learn: 9.9448491	total: 17.1s	remaining: 38.9s
306:	learn: 9.9445518	total: 17.2s	remaining: 38.8s
307:	learn: 9.9440919	total: 17.3s	remaining: 38.8s
308:	learn: 9.9438703	total: 17.3s	remaining: 38.7s
309:	learn: 9.9437393	total: 17.4s	remaining: 38.7s
310:	learn: 9.9435164	total: 17.4s	remaining: 38.6s
311:	learn: 9.9433352	total: 17.5s	remaining: 38.6s
312:	learn: 9.9430342	total: 17.6s	remaining: 38.5s
313:	learn: 9.9427731	total: 17.6s	remaining: 38.5s
314:	learn: 9.9424541	total: 17.7s	remaining: 38.4s
315:	learn: 9.9422792	total: 17.7s	remaining: 38.4s
316:	learn: 9.9420283	total: 17.8s	remaining: 38.4s
317:	learn: 9.9416914	total: 17.9s	remaining: 38.3s
318:	learn: 9.9413229	total: 17.9s	remaining: 38.3s
319:	learn: 9.9407925	total: 18s	remaining: 38.2s
320:	learn: 9.9403467	total: 18s	remaining: 38.1s
321:	learn: 9.9399436	total: 18.1s	remaining: 38.1s
322:	learn: 9.9396998	total: 18.1s	remaining: 38s
323:	learn: 9.9393280	total: 18.2s	remaining: 38s
324:	learn: 9.9390145	total: 18.3s	remaining: 37.9s
325:	learn: 9.9386291	total: 18.3s	remaining: 37.9s
326:	learn: 9.9383069	total: 18.4s	remaining: 37.8s
327:	learn: 9.9379625	total: 18.4s	remaining: 37.7s
328:	learn: 9.9376160	total: 18.5s	remaining: 37.7s
329:	learn: 9.9372307	total: 18.5s	remaining: 37.6s
330:	learn: 9.9368738	total: 18.6s	remaining: 37.6s
331:	learn: 9.9365608	total: 18.7s	remaining: 37.5s
332:	learn: 9.9363407	total: 18.7s	remaining: 37.5s
333:	learn: 9.9359336	total: 18.8s	remaining: 37.4s
334:	learn: 9.9355295	total: 18.8s	remaining: 37.4s
335:	learn: 9.9349492	total: 18.9s	remaining: 37.3s
336:	learn: 9.9347150	total: 18.9s	remaining: 37.3s
337:	learn: 9.9343503	total: 19s	remaining: 37.2s
338:	learn: 9.9340064	total: 19.1s	remaining: 37.2s
339:	learn: 9.9337261	total: 19.1s	remaining: 37.1s
340:	learn: 9.9332514	total: 19.2s	remaining: 37s
341:	learn: 9.9329092	total: 19.2s	remaining: 37s
342:	learn: 9.9327390	total: 19.3s	remaining: 36.9s
343:	learn: 9.9324290	total: 19.3s	remaining: 36.8s
344:	learn: 9.9321080	total: 19.4s	remaining: 36.8s
345:	learn: 9.9316875	total: 19.4s	remaining: 36.7s
346:	learn: 9.9313714	total: 19.5s	remaining: 36.6s
347:	learn: 9.9310519	total: 19.5s	remaining: 36.6s
348:	learn: 9.9307012	total: 19.6s	remaining: 36.5s
349:	learn: 9.9303362	total: 19.6s	remaining: 36.4s
350:	learn: 9.9301555	total: 19.7s	remaining: 36.4s
351:	learn: 9.9298200	total: 19.7s	remaining: 36.3s
352:	learn: 9.9295353	total: 19.8s	remaining: 36.3s
353:	learn: 9.9293307	total: 19.8s	remaining: 36.2s
354:	learn: 9.9289916	total: 19.9s	remaining: 36.1s
355:	learn: 9.9287152	total: 19.9s	remaining: 36.1s
356:	learn: 9.9283614	total: 20s	remaining: 36s
357:	learn: 9.9279560	total: 20s	remaining: 35.9s
358:	learn: 9.9276044	total: 20.1s	remaining: 35.9s
359:	learn: 9.9273634	total: 20.2s	remaining: 35.8s
360:	learn: 9.9272062	total: 20.2s	remaining: 35.8s
361:	learn: 9.9268468	total: 20.3s	remaining: 35.7s
362:	learn: 9.9263457	total: 20.3s	remaining: 35.7s
363:	learn: 9.9258961	total: 20.4s	remaining: 35.6s
364:	learn: 9.9256237	total: 20.4s	remaining: 35.5s
365:	learn: 9.9253536	total: 20.5s	remaining: 35.5s
366:	learn: 9.9251291	total: 20.5s	remaining: 35.4s
367:	learn: 9.9248216	total: 20.6s	remaining: 35.4s
368:	learn: 9.9245637	total: 20.6s	remaining: 35.3s
369:	learn: 9.9244683	total: 20.7s	remaining: 35.2s
370:	learn: 9.9241939	total: 20.7s	remaining: 35.2s
371:	learn: 9.9239453	total: 20.8s	remaining: 35.1s
372:	learn: 9.9236820	total: 20.9s	remaining: 35.1s
373:	learn: 9.9234289	total: 20.9s	remaining: 35s
374:	learn: 9.9231378	total: 21s	remaining: 35s
375:	learn: 9.9227732	total: 21s	remaining: 34.9s
376:	learn: 9.9224703	total: 21.1s	remaining: 34.8s
377:	learn: 9.9221394	total: 21.1s	remaining: 34.8s
378:	learn: 9.9218544	total: 21.2s	remaining: 34.7s
379:	learn: 9.9214882	total: 21.2s	remaining: 34.6s
380:	learn: 9.9210846	total: 21.3s	remaining: 34.6s
381:	learn: 9.9207579	total: 21.3s	remaining: 34.5s
382:	learn: 9.9204352	total: 21.4s	remaining: 34.5s
383:	learn: 9.9201123	total: 21.5s	remaining: 34.4s
384:	learn: 9.9196841	total: 21.5s	remaining: 34.4s
385:	learn: 9.9194679	total: 21.6s	remaining: 34.4s

In [14]:
grid.best_params_

{'random_state': 34}

In [15]:
grid.best_score_

-9.932770537104668

In [8]:
model.get_all_params()

{'nan_mode': 'Min',
 'eval_metric': 'RMSE',
 'iterations': 1000,
 'sampling_frequency': 'PerTree',
 'leaf_estimation_method': 'Newton',
 'random_score_type': 'NormalWithModelSizeDecrease',
 'grow_policy': 'SymmetricTree',
 'penalties_coefficient': 1,
 'boosting_type': 'Plain',
 'model_shrink_mode': 'Constant',
 'feature_border_type': 'GreedyLogSum',
 'bayesian_matrix_reg': 0.10000000149011612,
 'eval_fraction': 0,
 'force_unit_auto_pair_weights': False,
 'l2_leaf_reg': 3,
 'random_strength': 1,
 'rsm': 1,
 'boost_from_average': True,
 'model_size_reg': 0.5,
 'pool_metainfo_options': {'tags': {}},
 'subsample': 0.800000011920929,
 'use_best_model': False,
 'random_seed': 0,
 'depth': 6,
 'posterior_sampling': False,
 'border_count': 254,
 'classes_count': 0,
 'auto_class_weights': 'None',
 'sparse_features_conflict_fraction': 0,
 'leaf_estimation_backtracking': 'AnyImprovement',
 'best_model_min_trees': 1,
 'model_shrink_rate': 0,
 'min_data_in_leaf': 1,
 'loss_function': 'RMSE',
 'learning_rate': 0.11249399930238724,
 'score_function': 'Cosine',
 'task_type': 'CPU',
 'leaf_estimation_iterations': 1,
 'bootstrap_type': 'MVS',
 'max_leaves': 64}

In [17]:
display(model.score(X_test, y_test))
display(model.score(X_train, y_train))

0.8665673340117628

0.8702034823360925